# Generated by Django 5.1.2 on 2024-10-13 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="periodicity",
            field=models.CharField(
                choices=[
                    ("once", "Один раз"),
                    ("daily", "Раз в день"),
                    ("weekly", "Раз в неделю"),
                    ("monthly", "Раз в месяц"),
                ],
                max_length=10,
            ),
        ),
    ]
