# Generated by Django 5.1.2 on 2024-10-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0003_alter_mailingattempt_options_client_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={"permissions": [("can_disable_mailing", "Can Disable Mailing")]},
        ),
    ]
