# Generated by Django 5.1.2 on 2024-10-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0004_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_disable_mailing", "Can Disable Mailing"),
                    ("view_all_mailings", "Can View All Mailings"),
                ]
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("started", "Запущена"),
                    ("finished", "Завершена"),
                    ("disabled", "Выключена"),
                ],
                default="created",
                max_length=10,
            ),
        ),
    ]
