# Generated by Django 5.1.2 on 2024-10-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0005_alter_mailing_options_alter_mailing_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_disable_mailing", "Can Disable Mailing"),
                    ("view_all_mailings", "Can View All Mailings"),
                    ("can_edit_mailing", "Can Edit Mailing"),
                ]
            },
        ),
    ]
