# Generated by Django 5.1.2 on 2024-10-26 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0006_alter_mailing_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"permissions": [("can_edit_message", "Can Edit Message")]},
        ),
    ]
